on:
  workflow_dispatch:
    inputs:
      deploy_tag:
        description: "Which tag to deploy"
        required: true
        type: string
        default: "latest"
      docker:
        description: "Deploy to DockerHub"
        required: true
        type: boolean
        default: false
      deno:
        description: "Deploy to deno"
        required: true
        type: boolean
        default: false

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          load: true
          push: false
          tags: meting-api:${{ inputs.deploy_tag }}
          context: .

      - name: Test Docker image
        run: bash scripts/docker/test-docker.sh
        env:
          TAG: ${{ inputs.deploy_tag }}

      - name: Export Docker image
        run: docker save meting-api:${{ inputs.deploy_tag }} | gzip -1cf > meting.tar.gz

      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: meting.${{ inputs.deploy_tag }}.tar.gz
          path: meting.tar.gz
          retention-days: 1

  upload-art:
    needs: [test-docker]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm i
      - run: npm run build:all

      - uses: actions/upload-artifact@v3
        with:
          name: cloudflare-workers.js
          path: dist/cloudflare-workers.js
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: deno.js
          path: dist/deno.js
          retention-days: 1

  deploy-to-deno:
    needs: [upload-art]
    if: ${{ inputs.deno }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: deno.js
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: meting
          entrypoint: deno.js

  release-docker:
    needs: [test-docker]
    if: ${{ inputs.docker }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meting-api:${{ inputs.deploy_tag }}
          context: .
